---
# tasks file for k8s_endpoint
- name: copy endpoint to k8s_node
  template: src=gluster_endpoint.yaml.j2 dest=/tmp/gluster_endpoint.yaml owner=root group=root mode=0655
  when: inventory_hostname in groups['k8s_node'] and ansible_os_family == "RedHat"
  tags: k8s_node

#- name: create gluster_ep
#  k8s:
#    state: present
#    src: /tmp/gluster_endpoint.yaml
#  when: inventory_hostname in groups['k8s_node'] and ansible_os_family == "RedHat"
#  tags: k8s_node


- name: create gluster_ep
  shell: source /etc/profile && kubectl create -f /tmp/gluster_endpoint.yaml
  when: inventory_hostname in groups['k8s_node'] and ansible_os_family == "RedHat"
  tags: k8s_node

